---
- hostname: name={{ host_name }}

- name: Install common packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - vim
    - curl
    - yum-utils

- name: Set timezone to Asia/Ho_Chi_Minh
  timezone: name=Asia/Ho_Chi_Minh
